### ISSUE TITLE
Input files

### ISSUE THREAD

**Issue by anshumang** [anders-dc/sphere#10]
This is more of an user group question but not sure if there is a mailing list where I can post my query. I have been able to successfully compile sphere with nvcc 6.5 and gcc 4.8 on an ubuntu14.04 box with K40 GPU. I couldn't find instructions to generate the input files, do they need to be generated?

**Comment by anders-dc** [comment]
Hi Anshuman, thanks for getting in touch. 

With questions like these, I recommend using the project [Gitter chat](https://gitter.im/anders-dc/sphere) or getting in touch by [email](mailto:andersd@riseup.net).

The input files are generated using the `sphere` module that's in the ``python/sphere.py`` file. For a simple example, see ``python/collision.py``.

**Comment by anshumang** [comment]
Thanks @anders-dc :+1: 
I have sent you an email with my questions.
